name: Build and Deploy

on:
  push:
    branches:
      - main
  schedule:
    # rebuild website once an hour
    - cron:  '23 * * * *'


permissions:
  contents: write

jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - uses: cachix/install-nix-action@v20

      - name: Fetch API data
        env:
          PRETIX_TOKEN: ${{ secrets.PRETIX_TOKEN }}
        run: bash ./data/fetch.sh

      - name: Build
        run: |
          nix build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: result
